### ISSUE TITLE
Improvement / Feature Request: Randomize words

### ISSUE THREAD

**Issue by thamognya** [milesvw/msrewards-cheater#1]
### Random word generator

I suggest, since Microsoft rewards works on searching, you could just make a random word generator to make thousands of such words and increase the chances of getting a rewards, and also would make it faster. 

Also it would be better to change the user agent, to prevent bing to consider this as a bot

Change timing instead of constant one second.

The last two are to prevent captcha

**Comment by milesvw** [comment]
Do you know of any open source random word generators we could use? Also, wouldn't a random word generator just pick from a large list of words anyways?

One feature I'd like to add in the future is getting points on mobile as well. One way I was thinking of doing this was automatically opening Chrome dev tools and emulating a phone that way. It might be worth seeing if we could get the same effect by changing the user agent to a phone, but it is a good idea to change the user agents to prevent captchas too. 

So far, I haven't run into any issues with capchas, but it would definitely be worth randomizing the search speed.
